FROM scratch

VOLUME /app/var
VOLUME /app/src
EXPOSE 1337

ARG gomaxprocs="8"

WORKDIR /app

ENV TWITCHAUTHORIZATION="OAuth "
ENV TWITCHCLIENTID=""
ENV UNTAPPDTOKEN=""
ENV HTTPADDR="0.0.0.0:1337"

ENV TWITTERACCESSTOKEN=""
ENV TWITTERACCESSSECRET=""
ENV TWITTERCONSUMERKEY=""
ENV TWITTERCONSUMERSECRET=""

ENV AOCSESSION=""

ENV TWILIOTOKEN=""
ENV TWILIOSID=""
ENV TWILIONUMBER="+5558675309"

ENV TYPE=slackapp
ENV SLACKTOKEN=FOO
ENV SLACKUSERTOKEN=FOO
ENV SLACKVERIFICATION=FOO
ENV SLACKBOTID=FOO

ENV SLACKAPPLOGDIR=/app/var/logs
ENV SLACKAPPLOGMESSAGEDIR=/app/var/logs

ENV GOMAXPROCS=8

ADD . $SRC_DIR

ENV TZ America/New_York

COPY catbase /app/catbase

ENTRYPOINT ["/app/catbase", "-db=/app/var/catbase.db", "-debug"]
